### ISSUE TITLE
2024年6月緊急対応版

### ISSUE THREAD

**Issue by wan2355** [CSReviser/CaptureStream2#16]
深刻なエラーではありませんので、ご参考までに。

macOS：12.7.4
CaptureStream2:　6/4対応版

国内でVPNを利用しておりますが、6/17頃からVPNを使ったままですと、添付したようなエラーが生じます。
（NHKがアクセスを制限している可能性あり。）
この場合、以下のようにすれば、今のところは大丈夫です。

1. VPNを一時停止するか、解除。
2. CaptureStream2を再起動。
3. レコーディングを押す。
(4. 作業完了後にVPN再開。)

注意：
CaptureStream2を再起動をしないと、同じエラーが出ますので、ご注意ください。
海外からアクセスしている場合、どうなるか不明。

![2024-06-30_1200](https://github.com/CSReviser/CaptureStream2/assets/60186162/a9652c84-51ab-470a-b31b-c465c5227513)

### Discussed in https://github.com/CSReviser/CaptureStream2/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **CSReviser** June  4, 2024</sup>
2024年6月緊急対応版
＜全OS共通＞
（１）2024年6月3日(月)〜4日(火)の仕様変更に対応しました。
　　　旧JSONの更新停止　⇒　廃止　への対応。

※全ユーザーに更新適用が推奨されます。
※Mac版は動作確認していません。
※Mac版のバイナリは10.1x以前のOSに非対応です。必要な方は自分でビルドしてください。

<hr /><em>This discussion was created from the release <a href='https://github.com/CSReviser/CaptureStream2/releases/tag/20240604'>2024年6月緊急対応版</a>.</em></div>

**Comment by CSReviser** [comment]
Issue登録ありがとうございます。
「番組ID：6809_01のデータ取得エラー」（6809_01はラジオビジネス英語の番組ID）というメッセージはチェックを入れたボタンの、らじる★らじる番組の情報を取得できない場合に表示されます。
語学講座CS2はインターネット接続・構成の制御は行っていませんので、記載頂いた内容を拝見する限り、語学講座CS2としては仕様通りの期待された動作をしており、問題ないと考えます。

[らじる★らじる](https://www.nhk.or.jp/radio/ondemand/index_genre.html?genre=language)が再生できること、[よくあるご質問（らじる★らじる）](https://www.nhk.or.jp/radio/info/faq.html)、[NHK 音声再生確認ページ](https://www.nhk.or.jp/radio/soundcheck/)をご確認ください。

語学講座CS2の問題点の追加情報を頂けない場合は、下記のドキュメントにインターネット接続関連の追記をしましたので、これをもって本件Issueをクローズとさせていただきます。

[【必要要件】](https://csreviser.github.io/CaptureStream2/requirements)   ※「インターネット接続環境」を追記しました。
[【トラブルシューティング】](https://csreviser.github.io/CaptureStream2/troubleshooting)   ※「＜不具合現象と対応例＞」を追記しました。

**Comment by CSReviser** [comment]
・記載内容から語学講座CS2の仕様に沿った動作をしており、問題点は見受けられない。
・問題点についての追加情報がない。
・VPNを使うことに依存して発生している事から個別環境依存問題と考えられる。
・語学講座CS2はVPN接続環境の構築制御を行なっていない。
・ドキュメントに関連事項の追記を行った。

上記等によりこのIssueはcloseといたします。
